name: Full Data Refresh

on:
  # Weekly full refresh on Sunday at 2 AM ET (7 AM UTC)
  schedule:
    - cron: '0 7 * * 0'

  # Manual trigger option
  workflow_dispatch:

jobs:
  full-refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch FEC data (Full Refresh)
        env:
          FEC_API_KEY: ${{ secrets.FEC_API_KEY }}
        run: |
          echo "Starting full data refresh - this will take 17-18 hours"
          python fetch_fec_data.py

      - name: Load data to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python load_to_supabase.py

      - name: Log completion
        run: |
          echo "Full refresh completed at $(date)"
          echo "Candidates file size: $(du -h candidates_2026.json | cut -f1)"
          echo "Financials file size: $(du -h financials_2026.json | cut -f1)"

      - name: Upload artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: |
            progress.json
            *.log
          retention-days: 7

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Full data refresh failed. Check the logs for details."
